-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 17:18:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_Padle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_Padle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Padle` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_Padle` ;

-- -----------------------------------------------------
-- Table `bd_Padle`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`turno` (
  `idTurno` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `T1` VARCHAR(10) NOT NULL,
  `T2` VARCHAR(10) NOT NULL,
  `T3` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTurno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idTurno_UNIQUE` ON `bd_Padle`.`turno` (`idTurno` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`cancha` (
  `numero_cancha` INT NOT NULL AUTO_INCREMENT,
  `idTurno` INT NOT NULL,
  `superficie` VARCHAR(10) NOT NULL,
  `iluminacion` VARCHAR(2) NOT NULL,
  `techado` VARCHAR(2) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT NULL,
  `costo` INT NOT NULL,
  PRIMARY KEY (`numero_cancha`),
  CONSTRAINT `FK_canchaXturno`
    FOREIGN KEY (`idTurno`)
    REFERENCES `bd_Padle`.`turno` (`idTurno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idCancha_UNIQUE` ON `bd_Padle`.`cancha` (`numero_cancha` ASC) ;

CREATE INDEX `FK_canchaXturno_idx` ON `bd_Padle`.`cancha` (`idTurno` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idRol_UNIQUE` ON `bd_Padle`.`rol` (`idRol` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `DNI` INT NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `FK_usuarioXrol`
    FOREIGN KEY (`idRol`)
    REFERENCES `bd_Padle`.`rol` (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `bd_Padle`.`usuario` (`idUsuario` ASC) ;

CREATE INDEX `FK_usuarioXrol_idx` ON `bd_Padle`.`usuario` (`idRol` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`opinion` (
  `idOpinion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `puntuacion` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idOpinion`),
  CONSTRAINT `FK_opinionXusuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bd_Padle`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idOpinion_UNIQUE` ON `bd_Padle`.`opinion` (`idOpinion` ASC) ;

CREATE INDEX `FK_opinionXusuario_idx` ON `bd_Padle`.`opinion` (`idUsuario` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`pareja_torneo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`pareja_torneo` (
  `idPareja` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `nombre_par` VARCHAR(45) NOT NULL,
  `sexo_par` VARCHAR(10) NOT NULL,
  `fecha_nac_par` DATE NOT NULL,
  `contacto_par` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPareja`),
  CONSTRAINT `FK_parejaXusuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bd_Padle`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idParejas_UNIQUE` ON `bd_Padle`.`pareja_torneo` (`idPareja` ASC) ;

CREATE INDEX `FK_parejaXusuario_idx` ON `bd_Padle`.`pareja_torneo` (`idUsuario` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `numero_cancha` INT NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idReserva`),
  CONSTRAINT `FK_reservaXcancha`
    FOREIGN KEY (`numero_cancha`)
    REFERENCES `bd_Padle`.`cancha` (`numero_cancha`),
  CONSTRAINT `FK_reservaXusuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bd_Padle`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idReserva_UNIQUE` ON `bd_Padle`.`reserva` (`idReserva` ASC) ;

CREATE INDEX `FK_reservaXcancha_idx` ON `bd_Padle`.`reserva` (`numero_cancha` ASC) ;

CREATE INDEX `FK_reservaXusuario_idx` ON `bd_Padle`.`reserva` (`idUsuario` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`torneo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`torneo` (
  `idTorneo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tor` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTorneo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idTorneo_UNIQUE` ON `bd_Padle`.`torneo` (`idTorneo` ASC) ;


-- -----------------------------------------------------
-- Table `bd_Padle`.`torneoxpareja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Padle`.`torneoxpareja` (
  `idTorneoXPareja` INT NOT NULL AUTO_INCREMENT,
  `idPareja` INT NOT NULL,
  `idTorneo` INT NOT NULL,
  PRIMARY KEY (`idTorneoXPareja`),
  CONSTRAINT `FK_tpXpareja`
    FOREIGN KEY (`idPareja`)
    REFERENCES `bd_Padle`.`pareja_torneo` (`idPareja`),
  CONSTRAINT `FK_tpXtorneo`
    FOREIGN KEY (`idTorneo`)
    REFERENCES `bd_Padle`.`torneo` (`idTorneo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idTorneoXPareja_UNIQUE` ON `bd_Padle`.`torneoxpareja` (`idTorneoXPareja` ASC) ;

CREATE INDEX `FK_tpXtorneo_idx` ON `bd_Padle`.`torneoxpareja` (`idTorneo` ASC) ;

CREATE INDEX `FK_tpXpareja_idx` ON `bd_Padle`.`torneoxpareja` (`idPareja` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
